config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get "home/index"
  root "home#index"
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><% pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2 form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name,  class:"form-control" %>
  </div>

  <div class="mb-2">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name ,  class:"form-control"%>
  </div>

  <div class="fmb-2">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email,  class:"form-control" %>
  </div>

  <div class="mb-2">
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone,  class:"form-control" %>
  </div>

  <div class="mb-2">
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter,  class:"form-control" %>
  </div>

  <div class="mb-2">
    
    
    <%= form.number_field :user_id, id: :friend_user_id,  class:"form-control", value: current_user.id, type: :hidden  %>
  </div>

  <div class="mb-2">
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<% dom_id friend %>">
      <tr>
      <th scope="row"><%= friend.first_name %></th>
      <td><%= friend.last_name %></td>
      <td><%= friend.email %></td>
      <td><%= friend.phone%></td>
      <td><%= friend.twitter%></td>
      <td><%= friend.user_id%></td>
      <td><%= link_to "Show", friend, class:"btn btn-primary" %></td>
      </tr>
   

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-primary" %> |
  <%= link_to "Back to friends", friends_path , class:"btn btn-primary" %>
</div>

app/views/friends/index.html.erb
<h1>Friends</h1>

<div id="friends">
  
  <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    
   
    <% @friends.each do |friend| %>
    <%= render friend %>
    
    <% end %>

  
  </tbody>
</table>
  
</div>

<%= link_to "New friend", new_friend_path, class:"btn btn-primary"%>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>



<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-primary" %>
</div>

app/views/friends/show.html.erb
<%render @friend %>

<div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"><%= @friend.first_name %> <%= @friend.last_name %></h1>
        <p class="col-md-8 fs-4">
        <%= @friend.email%> |
        <%= @friend.phone%> |
        <%= @friend.twitter%>
        <%= @friend.user_id%>
        </p>
      </div>
    </div>


<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-primary"%> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-primary" %>  <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-primary mt-2" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link"%>
        </li>
        
         
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Friends', friends_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'New Friend', new_friend_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-light" %>
          
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to 'Sing In', new_user_session_path, class:"nav-link"%>
        </li>
        <%end%>

        
        
        
        
        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>Friends List</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

  </head>

  <body>
  <%= render "home/header" %>
  <div class="container">
  <br/>
  <% if notice %>
    <%= render 'layouts/alerts' %>
  <% end %>
  <br/>
    <%= yield %>
  </div>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>
   